BEGIN;

-- One row per source file.  The SHA-256 key makes importing the exact same
-- bytes idempotent while preserving lineage for every distinct source file.
CREATE TABLE IF NOT EXISTS public.organization_import_batches (
    import_batch_id UUID PRIMARY KEY,
    source_filename TEXT NOT NULL,
    source_sha256 TEXT NOT NULL UNIQUE,
    source_size_bytes BIGINT NOT NULL CHECK (source_size_bytes >= 0),
    status TEXT NOT NULL DEFAULT 'STAGING'
        CHECK (status IN (
            'STAGING',
            'VALIDATING',
            'VALIDATION_FAILED',
            'PROMOTING',
            'COMPLETED',
            'FAILED'
        )),
    total_rows INTEGER NOT NULL DEFAULT 0 CHECK (total_rows >= 0),
    valid_rows INTEGER NOT NULL DEFAULT 0 CHECK (valid_rows >= 0),
    invalid_rows INTEGER NOT NULL DEFAULT 0 CHECK (invalid_rows >= 0),
    promoted_rows INTEGER NOT NULL DEFAULT 0 CHECK (promoted_rows >= 0),
    error_summary JSONB NOT NULL DEFAULT '[]'::JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT organization_import_batches_sha256_format_ck
        CHECK (source_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT organization_import_batches_counts_ck
        CHECK (valid_rows + invalid_rows <= total_rows),
    CONSTRAINT organization_import_batches_errors_array_ck
        CHECK (jsonb_typeof(error_summary) = 'array')
);

-- Staging deliberately uses TEXT for every source column.  Invalid raw values
-- must be retained here and diagnosed, rather than being rejected by master
-- table constraints before they can be audited.
CREATE TABLE IF NOT EXISTS public.staging_organizations (
    organization_id TEXT,
    organization_name TEXT,
    organization_name_normalized TEXT,
    organization_name_search_key TEXT,
    organization_type_code TEXT,
    organization_level TEXT,
    parent_organization_id TEXT,
    province_name TEXT,
    management TEXT,

    import_batch_id UUID NOT NULL
        REFERENCES public.organization_import_batches(import_batch_id)
        ON DELETE CASCADE,
    row_number INTEGER NOT NULL CHECK (row_number >= 2),
    imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validation_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (validation_status IN ('PENDING', 'VALID', 'INVALID')),
    validation_errors JSONB NOT NULL DEFAULT '[]'::JSONB,

    PRIMARY KEY (import_batch_id, row_number),
    CONSTRAINT staging_organizations_errors_array_ck
        CHECK (jsonb_typeof(validation_errors) = 'array')
);

CREATE TABLE IF NOT EXISTS public.organizations (
    organization_id TEXT PRIMARY KEY,
    organization_name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    search_key TEXT NOT NULL,
    organization_type_code TEXT NOT NULL,
    organization_level TEXT NOT NULL,
    parent_organization_id TEXT,
    province_name TEXT NOT NULL,
    management TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT organizations_id_not_blank_ck
        CHECK (btrim(organization_id) <> ''),
    CONSTRAINT organizations_name_not_blank_ck
        CHECK (btrim(organization_name) <> ''),
    CONSTRAINT organizations_normalized_name_not_blank_ck
        CHECK (btrim(normalized_name) <> ''),
    CONSTRAINT organizations_search_key_not_blank_ck
        CHECK (btrim(search_key) <> ''),
    CONSTRAINT organizations_type_not_blank_ck
        CHECK (btrim(organization_type_code) <> ''),
    CONSTRAINT organizations_level_not_blank_ck
        CHECK (btrim(organization_level) <> ''),
    CONSTRAINT organizations_province_not_blank_ck
        CHECK (btrim(province_name) <> ''),
    CONSTRAINT organizations_management_ck
        CHECK (management IN ('BCA', 'BQP')),
    CONSTRAINT organizations_parent_not_self_ck
        CHECK (parent_organization_id IS NULL OR parent_organization_id <> organization_id),
    -- These levels are structurally subordinate in the registry.  A missing
    -- parent is data-quality debt and must never be guessed during import.
    CONSTRAINT organizations_child_parent_required_ck
        CHECK (
            organization_level NOT IN (
                'DISTRICT',
                'DISTRICT_DEPARTMENT',
                'PROVINCE_DEPARTMENT',
                'PROVINCE_BORDER',
                'BORDER_POST',
                'BORDER_SQUADRON'
            )
            OR parent_organization_id IS NOT NULL
        ),
    CONSTRAINT organizations_parent_fk
        FOREIGN KEY (parent_organization_id)
        REFERENCES public.organizations(organization_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.organization_aliases (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id TEXT NOT NULL
        REFERENCES public.organizations(organization_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    alias_name TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    alias_search_key TEXT NOT NULL,
    alias_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT organization_aliases_name_not_blank_ck
        CHECK (btrim(alias_name) <> ''),
    CONSTRAINT organization_aliases_normalized_not_blank_ck
        CHECK (btrim(normalized_alias) <> ''),
    CONSTRAINT organization_aliases_search_key_not_blank_ck
        CHECK (btrim(alias_search_key) <> ''),
    CONSTRAINT organization_aliases_type_ck
        CHECK (alias_type IN (
            'ABBREVIATION',
            'SHORT_NAME',
            'FORMER_NAME',
            'COMMON_NAME'
        )),
    CONSTRAINT organization_aliases_org_search_key_uq
        UNIQUE (organization_id, alias_search_key)
);

CREATE TABLE IF NOT EXISTS public.matching_test_cases (
    test_id TEXT PRIMARY KEY,
    query_name TEXT,
    query_id TEXT,
    province_name TEXT,
    organization_type TEXT,
    expected_organization_id TEXT
        REFERENCES public.organizations(organization_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    expected_match_status TEXT NOT NULL,
    expected_management TEXT,
    scenario TEXT NOT NULL,
    dataset_split TEXT NOT NULL DEFAULT 'DEV',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT matching_test_cases_id_not_blank_ck
        CHECK (btrim(test_id) <> ''),
    CONSTRAINT matching_test_cases_has_query_ck
        CHECK (
            NULLIF(btrim(query_id), '') IS NOT NULL
            OR NULLIF(btrim(query_name), '') IS NOT NULL
            OR expected_match_status = 'INVALID_INPUT'
        ),
    CONSTRAINT matching_test_cases_status_ck
        CHECK (expected_match_status IN (
            'EXACT_ID_MATCH',
            'EXACT_NAME_MATCH',
            'NORMALIZED_MATCH',
            'SEARCH_KEY_MATCH',
            'ALIAS_MATCH',
            'FUZZY_CANDIDATES',
            'FUZZY_MATCH',
            'AMBIGUOUS_MATCH',
            'NOT_FOUND',
            'INVALID_INPUT'
        )),
    CONSTRAINT matching_test_cases_management_ck
        CHECK (expected_management IS NULL OR expected_management IN ('BCA', 'BQP')),
    CONSTRAINT matching_test_cases_split_ck
        CHECK (dataset_split IN ('DEV', 'TEST')),
    CONSTRAINT matching_test_cases_expected_result_ck
        CHECK (
            (expected_match_status IN (
                'EXACT_ID_MATCH',
                'EXACT_NAME_MATCH',
                'NORMALIZED_MATCH',
                'SEARCH_KEY_MATCH',
                'ALIAS_MATCH',
                'FUZZY_MATCH'
            ) AND expected_organization_id IS NOT NULL AND expected_management IS NOT NULL)
            OR
            (expected_match_status IN (
                'FUZZY_CANDIDATES',
                'AMBIGUOUS_MATCH',
                'NOT_FOUND',
                'INVALID_INPUT'
            ))
        )
);

COMMIT;
